@startuml DiagramaCasosDeUso_1_SeguridadYUsuarios
left to right direction
skinparam shadowing false
skinparam roundcorner 6
scale 1.6

actor Usuario
actor Administrador
Administrador --|> Usuario

rectangle "Seguridad y Sesion" #FEFECE {
  usecase "Iniciar Sesion" as CU01
  usecase "Cerrar Sesion" as CU03
  usecase "Cambiar Contrasena" as CU04
  usecase "Cambiar Idioma" as CU05
  usecase "Restaurar Integridad\ndel Sistema" as CU02
}

rectangle "Gestion de Usuarios" #E8F4E8 {
  usecase "Crear Usuario" as CU06
  usecase "Eliminar Usuario" as CU07
  usecase "Desbloquear Usuario" as CU08
  usecase "Asignar Perfiles\na Usuario" as CU09
  usecase "Ver Historial\nde Usuario" as CU10
  usecase "Restaurar Usuario\ndesde Historial" as CU11
}

Usuario -- CU01
Usuario -- CU03
Usuario -- CU04
Usuario -- CU05

Administrador -- CU02
Administrador -- CU06
Administrador -- CU07
Administrador -- CU08
Administrador -- CU09
Administrador -- CU10
Administrador -- CU11
@enduml
